### ISSUE TITLE
Inline Editor warning prevents extension from working

### ISSUE THREAD

**Issue by lkcampbell** [peterflynn/brackets-regex-editor#9]
**OS:** Mac OSX Mavericks

**Brackets Version:** sprint 38 development build 0.38.0-0 (master c3f2b50b1)

**Extension Version:** 1.1.2

**Repro Steps:**
Try to use this extension in Sprint 38.

**Observed Results:**
An Inline Editor warning pops up: `JS Quick Edit: place cursor in function name`

**Expected Results:**
The extension should work.

**Comment by peterflynn** [comment]
It's not the warning that's breaking it -- it needs an update akin to peterflynn/copy-as-html@cc2522d4 to work with cmv4, and without that just it fails to recognize any regular expressions.  (And there's some layout stuff that broke due to cmv4 also).  I've had it all fixed locally for a while now, just need to get the update pushed out -- hopefully tonight.  Thanks for the reminder!

**Comment by peterflynn** [comment]
Fixed in version 1.1.3

Turns out the layout fixes I referenced above weren't needed (cmv4 must have fixed whatever bug that was before going gold), so I've backed out those parts of the diff.
